source 'https://rubygems.org'

gem 'activesupport'
gem 'capybara', '2.7.1'
gem 'capybara-screenshot', :group => :test
gem 'cucumber'
gem 'pry'
gem 'parallel_tests'
gem 'phantomjs'
gem 'phantomjs-binaries'
gem 'poltergeist'
gem 'report_builder'
gem 'rspec'
gem 'rspec-retry'
gem 'selenium-webdriver', '2.53.4'
gem 'show_me_the_cookies'
gem 'site_prism'
gem 'slowhandcuke'
gem 'rake'
gem 'httparty'